export const BREAK_POINT_DEVICE_TABLET = 720;
export const BREAK_POINT_DEVICE_DESKTOP = 1280;
export const DEVICE_MOBILE = 'DEVICE_BY_SIZE_MOBILE';
export const DEVICE_TABLET = 'DEVICE_BY_SIZE_TABLET';
export const DEVICE_DESKTOP = 'DEVICE_BY_SIZE_DESKTOP';
